from app.tools.file_saver import save_files
from app.core.logger import log_event
from app.telemetry.factory_logger import emit_factory_event
from app.telemetry.translator import translate_to_domino_ticker
import os
import json
from datetime import datetime, timezone
from app.core.llm import call_llm
from app.core.constants import MAX_QA_ATTEMPTS

def _approval_context_for_attempt(attempts: int) -> str:
    return "qa_exhausted" if attempts >= MAX_QA_ATTEMPTS else "qa_retry"

def qa_agent(state):
    attempts = (state.get("attempts") or 0) + 1
    attempt_label = "Initial Build" if attempts == 1 else f"Retry {attempts-1}"
    thread_id = state.get("thread_id", "run-1")
    target_app_id = state.get("target_app_id")

    emit_factory_event(
        run_id=thread_id,
        module_id="MODULE_4_GRADLE",
        domino_step=6,
        domino_name="Self-Healing Workshop",
        state="WORKING",
        plain_english_translation=translate_to_domino_ticker("MODULE_4_GRADLE", "WORKING")
    )

    code = state.get("code", "")
    if not code:
        final_logs = log_event(state, "├─ [QA] ❌ Failed — no code to test")
        emit_factory_event(
            run_id=thread_id,
            module_id="MODULE_4_GRADLE",
            domino_step=6,
            domino_name="Self-Healing Workshop",
            state="FAILED",
            plain_english_translation="QA Failed: No code was generated."
        )
        return {
            "test_result": "fail",
            "attempts": attempts,
            "error_logs": "No code was generated by dev agent",
            "approval_context": _approval_context_for_attempt(attempts),
            "logs": final_logs["logs"]
        }

    from app.tools.file_saver import save_files
    
    # Save the generated files to the workspace (overwriting matching files)
    saved_files = save_files(code)

    if not saved_files:
        final_logs = log_event(state, "├─ [QA] ❌ Failed — no valid files parsed from LLM output")
        emit_factory_event(
            run_id=thread_id,
            module_id="MODULE_4_GRADLE",
            domino_step=6,
            domino_name="Self-Healing Workshop",
            state="FAILED",
            plain_english_translation="QA Failed: No valid files parsed."
        )
        return {
            "test_result": "fail",
            "attempts": attempts,
            "error_logs": "LLM output did not contain valid FILE: blocks with code. Ensure you use FILE: path/to/file followed by the file content (ideally inside ``` code blocks).",
            "approval_context": _approval_context_for_attempt(attempts),
            "logs": final_logs["logs"]
        }

    from app.tools.android_builder import run_gradle_build, run_static_analysis, cleanup_workspace
    
    project_path = "workspace"
    
    # --- 1. Static Analysis Check (ktlint & detekt) ---
    print(f"├─ [QA_DEBUG] Running Static Analysis in {project_path}...")
    static_result = run_static_analysis(project_path)
    
    if not static_result["success"]:
        test_result = "fail"
        print(f"├─ [QA_DEBUG] Static Analysis FAILED! Return code: {static_result.get('returncode', 'Unknown')}")
        final_logs = log_event(state, f"├─ [QA] ❌ Failed — Static Analysis error (attempt {attempts}/{MAX_QA_ATTEMPTS})")
        
        full_logs = f"STATIC ANALYSIS ERROR (ktlint/detekt):\n{static_result.get('error', '')}\n{static_result.get('output', '')}"
        error_logs = "...[Logs truncated]...\n" + full_logs[-4000:] if len(full_logs) > 4000 else full_logs
        approval_context = _approval_context_for_attempt(attempts)
        
        state_val = "REPAIRING" if attempts < 3 else "FAILED"
        emit_factory_event(
            run_id=thread_id,
            module_id="MODULE_4_GRADLE",
            domino_step=6,
            domino_name="Self-Healing Workshop",
            state=state_val,
            plain_english_translation=translate_to_domino_ticker("MODULE_4_GRADLE", state_val, "Static analysis found code smells.")
        )
        try:
            with open("error_logs.txt", "w") as f:
                f.write(error_logs)
            print(f"├─ [QA_DEBUG] Static Analysis error log saved to error_logs.txt")
        except Exception:
            pass
    else:
        # --- 2. KMP Compilation Check ---
        print(f"├─ [QA_DEBUG] Running Gradle build in {project_path} for app {target_app_id}...")
        build_result = run_gradle_build(project_path, app_id=target_app_id)
        
        if build_result["success"]:
            test_result = "pass"
            print(f"├─ [QA_DEBUG] Build SUCCESS!")
            final_logs = log_event(state, f"├─ [QA] ✅ Passed — Project compiled successfully (attempt {attempts}/{MAX_QA_ATTEMPTS})")
            
            # --- AUTONOMOUS REFLECTION ENGINE ---
            if attempts > 1 and state.get("error_logs"):
                print("├─ [QA_DEBUG] Extracting Lesson Learned via Reflection...")
                reflection_prompt = f"""
                You are a senior Kotlin Multiplatform architect.
                The previous code failed compilation with this error:
                {state.get("error_logs")}
                
                The developer successfully fixed it with this new code:
                {state.get("code")}
                
                Identify the EXACT core mistake that caused the compilation error, and extract a single, concise 'Lesson Learned' rule to prevent this from ever happening again.
                Examples: "Always explicitly import Modifier in Compose." or "Never use wildcard imports in KMP."
                Output ONLY the 1-sentence rule. No conversational text.
                """
                try:
                    lesson_text = call_llm(reflection_prompt, max_tokens=100).strip()
                    if lesson_text:
                        lessons_file = "app/resources/lessons_learned.json"
                        if os.path.exists(lessons_file):
                            with open(lessons_file, "r") as f:
                                lessons = json.load(f)
                        else:
                            lessons = []
                        
                        # Extract a short error signature
                        error_sig = state.get("error_logs", "").split("\\n")[0][:100]
                        
                        lessons.append({
                            "lesson": lesson_text,
                            "domain": "Android/KMP",
                            "model": "gpt-4o", # Default fallback, though we could pull from state config
                            "error_signature": error_sig,
                            "timestamp": datetime.now(timezone.utc).isoformat()
                        })
                        
                        with open(lessons_file, "w") as f:
                            json.dump(lessons, f, indent=4)
                        print(f"├─ [QA_DEBUG] Lesson Saved: {lesson_text}")
                except Exception as e:
                    print(f"├─ [QA_DEBUG] Failed to extract lesson: {e}")
            
            error_logs = ""
            approval_context = "qa_passed"
            
            # --- 3. Workspace Garbage Collection ---
            cleanup_workspace(project_path, app_id=target_app_id)
            
            emit_factory_event(
                run_id=thread_id,
                module_id="MODULE_4_GRADLE",
                domino_step=6,
                domino_name="Self-Healing Workshop",
                state="PASSED",
                plain_english_translation=translate_to_domino_ticker("MODULE_4_GRADLE", "PASSED")
            )
        else:
            test_result = "fail"
            print(f"├─ [QA_DEBUG] Build FAILED! Return code: {build_result.get('returncode', 'Unknown')}")
            final_logs = log_event(state, f"├─ [QA] ❌ Failed — Compilation error (attempt {attempts}/{MAX_QA_ATTEMPTS})")
            
            full_logs = f"COMPILATION ERROR:\n{build_result.get('error', '')}\n{build_result.get('output', '')}"
            error_logs = "...[Logs truncated]...\n" + full_logs[-4000:] if len(full_logs) > 4000 else full_logs
            
            if "no such file" in error_logs.lower() or "not found" in error_logs.lower():
                error_logs += "\nTip: Ensure the Dev Agent generates gradlew wrapper files or a valid build script."
    
            approval_context = _approval_context_for_attempt(attempts)
            
            state_val = "REPAIRING" if attempts < 3 else "FAILED"
            emit_factory_event(
                run_id=thread_id,
                module_id="MODULE_4_GRADLE",
                domino_step=6,
                domino_name="Self-Healing Workshop",
                state=state_val,
                plain_english_translation=translate_to_domino_ticker("MODULE_4_GRADLE", state_val, "Compilation error caught.")
            )

            try:
                with open("error_logs.txt", "w") as f:
                    f.write(error_logs)
                print(f"├─ [QA_DEBUG] Full error log saved to error_logs.txt")
            except Exception:
                pass
                
            if attempts == 4:
                print("├─ [QA_DEBUG] Max retries hit. Filing Autonomous GitHub Bug Report...")
                from app.tools.github_integration import file_github_issue
                issue_body = f"PipelineX encountered an unrecoverable failure during QA for {target_app_id}.\n\n### Error Logs\n```text\n{error_logs}\n```\n\n### PRD Context\n{state.get('prd', 'N/A')}\n\n### Attempted Code\n```kotlin\n{state.get('code', 'N/A')}\n```"
                file_github_issue(
                    title=f"[Autonomous Factory Bug] Compilation Failed for {target_app_id}",
                    body=issue_body
                )

    return {
        "attempts": attempts,
        "test_result": test_result,
        "error_logs": error_logs,
        "approval_context": approval_context,
        "logs": final_logs["logs"]
    }
