from app.tools.file_saver import save_files
import os

def qa_agent(state):
    attempts = (state.get("attempts") or 0) + 1

    print("│")
    print(f"├─ [QA] 🧪 Started — validating web build (attempt {attempts}/3)...")

    code = state.get("code", "")
    if not code:
        print("├─ [QA] ❌ Failed — no code to test")
        return {
            "test_result": "fail",
            "attempts": attempts,
            "error_logs": "No code was generated by dev agent"
        }

    saved_files = save_files(code)

    if not saved_files:
        print("├─ [QA] ❌ Failed — no valid files parsed from LLM output")
        return {
            "test_result": "fail",
            "attempts": attempts,
            "error_logs": "LLM output did not contain valid FILE: blocks"
        }

    # --- Web Validation Logic ---
    # Check for mandatory files
    has_html = any(f.endswith("index.html") for f in saved_files)
    
    if has_html:
        test_result = "pass"
        print(f"├─ [QA] ✅ Passed — index.html found (attempt {attempts}/3)")
        error_logs = ""
    else:
        test_result = "fail"
        print(f"├─ [QA] ❌ Failed — index.html missing (attempt {attempts}/3)")
        error_logs = "Critical file 'index.html' is missing from the generated files."

    return {
        "attempts": attempts,
        "test_result": test_result,
        "error_logs": error_logs
    }